version: '3.8'

services:
    whisper-at-server:
    image: 214882929820.dkr.ecr.us-east-1.amazonaws.com/v5_lines/whisper-at-server:v1.1.7
    container_name: whisper-at-server
    ports:
      - "9007:9007"
    networks:
      - whisper-net
    environment:
      WORKERS: 4
      PORT: 9007
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9007/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

