version: '3.8'

services:
  whisper-at-server:
    image: 214882929820.dkr.ecr.us-east-1.amazonaws.com/v5_lines/whisper-at-server:v1.0.19
    container_name: whisper-at-server
    ports:
      - "9007:9007"
    networks:
      whisper-net:
        aliases:
          - backend9007
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - WORKERS=4  # 👈 You can now change this in one place
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ./temp:/workspace/temp
    restart: unless-stopped
    command: sh -c "uvicorn server:app --host 0.0.0.0 --port 9007 --workers 4"

networks:
  whisper-net:
    driver: bridge

